% IdealDoc
% 
% In the Neural Ring Paper, we have some algorithms dealing with pseudo
% monomial ideals.  Here we discuss how such an ideal can be translated to 
% a matrix and back, and some operations one can do with that matrix with the
% corresponding ideal operations.
% 
% First, we assume our pseudo-monomial ideal is given as a set of generating
% pseudo-monomials on n variables x1,....,xn. I.e., each generator
%  is a product of terms of the form xi or 1-xi.
% As it is a pseudo-monomial ideal, no generator will have both these terms for
% the same i.  This allows us to equate a generator with a row n-vector, where
% the i'th entry is 1 if xi is in the product, 0 if 1-xi is in the product,
% and 2 if neither.
% Then, the matrix corresponding to the ideal can be made as the matrix
% with one such row corresponding to each generator.

% As an example, if n=3, and the ideal is generated by x1(1-x3), x2, x1x2,
% then we have the corresponding matrix  J=[1,2,0; 2,1,2; 1,1,2].  Clearly, one
% can take such a matrix and acquire from it the set of generators it 
% represents by interpreting each row as a polynomial.
% As the set of generators of  an ideal is not
% unique, there is more than one matrix corresponding to a particular
% ideal.

% We assume a p-m ideal is prime exactly when its set of generators are all
% linear and no indices are repeated.  To test for each generator being
% linear, we can check that in the corresponding matrix, each row has
% exactly one non-2 entry.

% To check if a p-m ideal is not proper, we test if it has 1 as a
% generator.  This corresponds to checking if our corresponding matrix has
% an all-2's row. Note that another way it could fail to be proper is if it
% had both x_i and 1-x_i as generators. The not-proper test doesn't check
% for this unfortunately. However,
% given a matrix which we already know has only linear generators, we have 
% the following additional test for proper-ness: if both xi and 1-xi appear
% for any i, then the ideal cannot be proper.  So we check each column of
% the corresponding matrix to see if any has both a 1 and a 0; if any does,
% then the ideal is not proper.

% To get rid of repeat generators or generators which are multiples of
% others, we compare rows.  If two rows are identical, they represent the
% same generator and so one may be removed without changing the ideal.
% Similarly, note that for example once we have x1x2 =(1,1,2,) in the ideal,
% then the pseudo-monomial x1x2x3 = (1,1,1) is already in the ideal, so
% this generator is not necessary.  So if rows A and B agree on the non-2 entries of A,
% then B represents a multiple of A, and B may be deleted without affecting
% the ideal.
